logging:
  level:
    fr:
      barbebroux:
        ghibliencyclopedia: INFO
spring:
  application:
    name: ghibliEncyclopedia
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8080
