logging:
  level:
    fr:
      barbebroux:
        ghibliencyclopedia: INFO
spring:
  application:
    name: ghibliEncyclopedia
  datasource:
    url: jdbc:h2:mem:favoritesDB
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_absent
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
server:
  port: 8080

movie:
  api:
    host: ${MOVIE_API_HOST:https://ghibliapi.vercel.app}
